project_id = "ijsrczmuaerwmlkmnhxz"

[api]
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://ijsrczmuaerwmlkmnhxz.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
enable_signup = true
